version: '3'
services:
    app:
        build: .

    loadbalancer:
        image: 'dockercloud/haproxy:latest'
        links:
            - app
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 80:80
    redis:
        image: "redis:alpine"
